### ISSUE TITLE
Error when don't use https_enabled and don't fill certification filepath

### ISSUE THREAD

**Issue by overskylab** [opsta/ansible-influxdb#2]
Task error when set 
```
#...snipped
http:
    https-enabled: false
    https-certificate: ''
    https-private-key: ''
    #...snipped
```
